// Code generated by mockery v2.42.1. DO NOT EDIT.

package client_mocks

import (
	context "context"

	client "github.com/blackstork-io/fabric/internal/splunk/client"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CreateSearchJob provides a mock function with given fields: ctx, req
func (_m *Client) CreateSearchJob(ctx context.Context, req *client.CreateSearchJobReq) (*client.CreateSearchJobRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSearchJob")
	}

	var r0 *client.CreateSearchJobRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.CreateSearchJobReq) (*client.CreateSearchJobRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.CreateSearchJobReq) *client.CreateSearchJobRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.CreateSearchJobRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.CreateSearchJobReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_CreateSearchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSearchJob'
type Client_CreateSearchJob_Call struct {
	*mock.Call
}

// CreateSearchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - req *client.CreateSearchJobReq
func (_e *Client_Expecter) CreateSearchJob(ctx interface{}, req interface{}) *Client_CreateSearchJob_Call {
	return &Client_CreateSearchJob_Call{Call: _e.mock.On("CreateSearchJob", ctx, req)}
}

func (_c *Client_CreateSearchJob_Call) Run(run func(ctx context.Context, req *client.CreateSearchJobReq)) *Client_CreateSearchJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.CreateSearchJobReq))
	})
	return _c
}

func (_c *Client_CreateSearchJob_Call) Return(_a0 *client.CreateSearchJobRes, _a1 error) *Client_CreateSearchJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_CreateSearchJob_Call) RunAndReturn(run func(context.Context, *client.CreateSearchJobReq) (*client.CreateSearchJobRes, error)) *Client_CreateSearchJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchJobByID provides a mock function with given fields: ctx, req
func (_m *Client) GetSearchJobByID(ctx context.Context, req *client.GetSearchJobByIDReq) (*client.GetSearchJobByIDRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchJobByID")
	}

	var r0 *client.GetSearchJobByIDRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetSearchJobByIDReq) (*client.GetSearchJobByIDRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetSearchJobByIDReq) *client.GetSearchJobByIDRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetSearchJobByIDRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.GetSearchJobByIDReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetSearchJobByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchJobByID'
type Client_GetSearchJobByID_Call struct {
	*mock.Call
}

// GetSearchJobByID is a helper method to define mock.On call
//   - ctx context.Context
//   - req *client.GetSearchJobByIDReq
func (_e *Client_Expecter) GetSearchJobByID(ctx interface{}, req interface{}) *Client_GetSearchJobByID_Call {
	return &Client_GetSearchJobByID_Call{Call: _e.mock.On("GetSearchJobByID", ctx, req)}
}

func (_c *Client_GetSearchJobByID_Call) Run(run func(ctx context.Context, req *client.GetSearchJobByIDReq)) *Client_GetSearchJobByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.GetSearchJobByIDReq))
	})
	return _c
}

func (_c *Client_GetSearchJobByID_Call) Return(_a0 *client.GetSearchJobByIDRes, _a1 error) *Client_GetSearchJobByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetSearchJobByID_Call) RunAndReturn(run func(context.Context, *client.GetSearchJobByIDReq) (*client.GetSearchJobByIDRes, error)) *Client_GetSearchJobByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSearchJobResults provides a mock function with given fields: ctx, req
func (_m *Client) GetSearchJobResults(ctx context.Context, req *client.GetSearchJobResultsReq) (*client.GetSearchJobResultsRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSearchJobResults")
	}

	var r0 *client.GetSearchJobResultsRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetSearchJobResultsReq) (*client.GetSearchJobResultsRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.GetSearchJobResultsReq) *client.GetSearchJobResultsRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.GetSearchJobResultsRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.GetSearchJobResultsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetSearchJobResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSearchJobResults'
type Client_GetSearchJobResults_Call struct {
	*mock.Call
}

// GetSearchJobResults is a helper method to define mock.On call
//   - ctx context.Context
//   - req *client.GetSearchJobResultsReq
func (_e *Client_Expecter) GetSearchJobResults(ctx interface{}, req interface{}) *Client_GetSearchJobResults_Call {
	return &Client_GetSearchJobResults_Call{Call: _e.mock.On("GetSearchJobResults", ctx, req)}
}

func (_c *Client_GetSearchJobResults_Call) Run(run func(ctx context.Context, req *client.GetSearchJobResultsReq)) *Client_GetSearchJobResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.GetSearchJobResultsReq))
	})
	return _c
}

func (_c *Client_GetSearchJobResults_Call) Return(_a0 *client.GetSearchJobResultsRes, _a1 error) *Client_GetSearchJobResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetSearchJobResults_Call) RunAndReturn(run func(context.Context, *client.GetSearchJobResultsReq) (*client.GetSearchJobResultsRes, error)) *Client_GetSearchJobResults_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
