# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 1

project_name: fabric

env:
  - CGO_ENABLED=0

builds:
  # CLI

  - id: fabric
    main: .
    binary: fabric
    flags: "-trimpath"
    ldflags:
      - -s -w
      - -X github.com/blackstork-io/fabric/cmd.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin

  # Plugins

  - id: elasticsearch
    main: ./internal/elasticsearch/cmd
    binary: "plugins/blackstork/elasticsearch@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: github
    main: ./internal/github/cmd
    binary: "plugins/blackstork/github@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: graphql
    main: ./internal/graphql/cmd
    binary: "plugins/blackstork/graphql@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: openai
    main: ./internal/openai/cmd
    binary: "plugins/blackstork/openai@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: opencti
    main: ./internal/opencti/cmd
    binary: "plugins/blackstork/opencti@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: postgresql
    main: ./internal/postgresql/cmd
    binary: "plugins/blackstork/postgresql@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: sqlite
    main: ./internal/sqlite/cmd
    binary: "plugins/blackstork/sqlite@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

  - id: terraform
    main: ./internal/terraform/cmd
    binary: "plugins/blackstork/terraform@{{ .Version }}"
    flags: "-trimpath"
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: fabric
    format: tar.gz
    builds:
      - fabric
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

  - id: plugins
    format: tar.gz
    builds:
      - elasticsearch
      - github
      - graphql
      - openai
      - opencti
      - postgresql
      - sqlite
      - terraform
    name_template: >-
      plugins_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
