with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internalpkg" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  github.com/blackstork-io/fabric/parser/definitions:
    config:
      recursive: true
    interfaces:
      FabricBlock:
  github.com/blackstork-io/fabric/internal/github:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/openai/client:
    config:
    interfaces:
      Client: