with-expecter: true
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internalpkg" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  github.com/blackstork-io/fabric/parser/definitions:
    config:
      recursive: true
    interfaces:
      FabricBlock:
  github.com/blackstork-io/fabric/internal/github:
    config:
    interfaces:
      Client:
      IssuesClient:
      GistClient:
  github.com/blackstork-io/fabric/internal/openai/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/hackerone/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/virustotal/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/splunk/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/nistnvd/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/elastic/kbclient:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/snyk/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/internal/microsoft/client:
    config:
    interfaces:
      Client:
  github.com/blackstork-io/fabric/plugin/resolver:
    config:
      inpackage: true
      dir: "./plugin/resolver"
      mockname: "mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      filename: "mock_{{.InterfaceName | snakecase}}_test.go"
    interfaces:
      Source: