// Code generated by mockery v2.52.2. DO NOT EDIT.

package client_mocks

import (
	context "context"

	client "github.com/blackstork-io/fabric/internal/iris/client"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ListAlerts provides a mock function with given fields: ctx, req
func (_m *Client) ListAlerts(ctx context.Context, req *client.ListAlertsReq) (*client.ListAlertsRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAlerts")
	}

	var r0 *client.ListAlertsRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ListAlertsReq) (*client.ListAlertsRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.ListAlertsReq) *client.ListAlertsRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ListAlertsRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.ListAlertsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlerts'
type Client_ListAlerts_Call struct {
	*mock.Call
}

// ListAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *client.ListAlertsReq
func (_e *Client_Expecter) ListAlerts(ctx interface{}, req interface{}) *Client_ListAlerts_Call {
	return &Client_ListAlerts_Call{Call: _e.mock.On("ListAlerts", ctx, req)}
}

func (_c *Client_ListAlerts_Call) Run(run func(ctx context.Context, req *client.ListAlertsReq)) *Client_ListAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ListAlertsReq))
	})
	return _c
}

func (_c *Client_ListAlerts_Call) Return(_a0 *client.ListAlertsRes, _a1 error) *Client_ListAlerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListAlerts_Call) RunAndReturn(run func(context.Context, *client.ListAlertsReq) (*client.ListAlertsRes, error)) *Client_ListAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListCases provides a mock function with given fields: ctx, req
func (_m *Client) ListCases(ctx context.Context, req *client.ListCasesReq) (*client.ListCasesRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCases")
	}

	var r0 *client.ListCasesRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.ListCasesReq) (*client.ListCasesRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *client.ListCasesReq) *client.ListCasesRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ListCasesRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *client.ListCasesReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListCases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCases'
type Client_ListCases_Call struct {
	*mock.Call
}

// ListCases is a helper method to define mock.On call
//   - ctx context.Context
//   - req *client.ListCasesReq
func (_e *Client_Expecter) ListCases(ctx interface{}, req interface{}) *Client_ListCases_Call {
	return &Client_ListCases_Call{Call: _e.mock.On("ListCases", ctx, req)}
}

func (_c *Client_ListCases_Call) Run(run func(ctx context.Context, req *client.ListCasesReq)) *Client_ListCases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*client.ListCasesReq))
	})
	return _c
}

func (_c *Client_ListCases_Call) Return(_a0 *client.ListCasesRes, _a1 error) *Client_ListCases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListCases_Call) RunAndReturn(run func(context.Context, *client.ListCasesReq) (*client.ListCasesRes, error)) *Client_ListCases_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
