// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pluginapi/v1/hcl.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int64                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column        int64                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Byte          int64                  `protobuf:"varint,3,opt,name=byte,proto3" json:"byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pos) Reset() {
	*x = Pos{}
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_hcl_proto_rawDescGZIP(), []int{0}
}

func (x *Pos) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Pos) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Pos) GetByte() int64 {
	if x != nil {
		return x.Byte
	}
	return 0
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Start         *Pos                   `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Pos                   `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_hcl_proto_rawDescGZIP(), []int{1}
}

func (x *Range) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Range) GetStart() *Pos {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Range) GetEnd() *Pos {
	if x != nil {
		return x.End
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      int64                  `protobuf:"varint,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Subject       *Range                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Context       *Range                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_hcl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_hcl_proto_rawDescGZIP(), []int{2}
}

func (x *Diagnostic) GetSeverity() int64 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Diagnostic) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Diagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Diagnostic) GetSubject() *Range {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Diagnostic) GetContext() *Range {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_pluginapi_v1_hcl_proto protoreflect.FileDescriptor

const file_pluginapi_v1_hcl_proto_rawDesc = "" +
	"\n" +
	"\x16pluginapi/v1/hcl.proto\x12\fpluginapi.v1\"E\n" +
	"\x03Pos\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x03R\x04line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x03R\x06column\x12\x12\n" +
	"\x04byte\x18\x03 \x01(\x03R\x04byte\"q\n" +
	"\x05Range\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12'\n" +
	"\x05start\x18\x02 \x01(\v2\x11.pluginapi.v1.PosR\x05start\x12#\n" +
	"\x03end\x18\x03 \x01(\v2\x11.pluginapi.v1.PosR\x03end\"\xb8\x01\n" +
	"\n" +
	"Diagnostic\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\x03R\bseverity\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12-\n" +
	"\asubject\x18\x04 \x01(\v2\x13.pluginapi.v1.RangeR\asubject\x12-\n" +
	"\acontext\x18\x05 \x01(\v2\x13.pluginapi.v1.RangeR\acontextB\xae\x01\n" +
	"\x10com.pluginapi.v1B\bHclProtoP\x01Z?github.com/blackstork-io/fabric/plugin/pluginapi/v1;pluginapiv1\xa2\x02\x03PXX\xaa\x02\fPluginapi.V1\xca\x02\fPluginapi\\V1\xe2\x02\x18Pluginapi\\V1\\GPBMetadata\xea\x02\rPluginapi::V1b\x06proto3"

var (
	file_pluginapi_v1_hcl_proto_rawDescOnce sync.Once
	file_pluginapi_v1_hcl_proto_rawDescData []byte
)

func file_pluginapi_v1_hcl_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_hcl_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_hcl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_v1_hcl_proto_rawDesc), len(file_pluginapi_v1_hcl_proto_rawDesc)))
	})
	return file_pluginapi_v1_hcl_proto_rawDescData
}

var file_pluginapi_v1_hcl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pluginapi_v1_hcl_proto_goTypes = []any{
	(*Pos)(nil),        // 0: pluginapi.v1.Pos
	(*Range)(nil),      // 1: pluginapi.v1.Range
	(*Diagnostic)(nil), // 2: pluginapi.v1.Diagnostic
}
var file_pluginapi_v1_hcl_proto_depIdxs = []int32{
	0, // 0: pluginapi.v1.Range.start:type_name -> pluginapi.v1.Pos
	0, // 1: pluginapi.v1.Range.end:type_name -> pluginapi.v1.Pos
	1, // 2: pluginapi.v1.Diagnostic.subject:type_name -> pluginapi.v1.Range
	1, // 3: pluginapi.v1.Diagnostic.context:type_name -> pluginapi.v1.Range
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_hcl_proto_init() }
func file_pluginapi_v1_hcl_proto_init() {
	if File_pluginapi_v1_hcl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_v1_hcl_proto_rawDesc), len(file_pluginapi_v1_hcl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_hcl_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_hcl_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_hcl_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_hcl_proto = out.File
	file_pluginapi_v1_hcl_proto_goTypes = nil
	file_pluginapi_v1_hcl_proto_depIdxs = nil
}
