// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: pluginapi/v1/spec.proto

package pluginapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Spec_Attr
	//	*Spec_Block
	//	*Spec_ObjSpec
	//	*Spec_ObjDump
	//	*Spec_Opaque
	Data isSpec_Data `protobuf_oneof:"data"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (m *Spec) GetData() isSpec_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Spec) GetAttr() *Attr {
	if x, ok := x.GetData().(*Spec_Attr); ok {
		return x.Attr
	}
	return nil
}

func (x *Spec) GetBlock() *Block {
	if x, ok := x.GetData().(*Spec_Block); ok {
		return x.Block
	}
	return nil
}

func (x *Spec) GetObjSpec() *Object {
	if x, ok := x.GetData().(*Spec_ObjSpec); ok {
		return x.ObjSpec
	}
	return nil
}

func (x *Spec) GetObjDump() *ObjDump {
	if x, ok := x.GetData().(*Spec_ObjDump); ok {
		return x.ObjDump
	}
	return nil
}

func (x *Spec) GetOpaque() *Opaque {
	if x, ok := x.GetData().(*Spec_Opaque); ok {
		return x.Opaque
	}
	return nil
}

type isSpec_Data interface {
	isSpec_Data()
}

type Spec_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type Spec_Block struct {
	Block *Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type Spec_ObjSpec struct {
	ObjSpec *Object `protobuf:"bytes,3,opt,name=obj_spec,json=objSpec,proto3,oneof"`
}

type Spec_ObjDump struct {
	ObjDump *ObjDump `protobuf:"bytes,4,opt,name=obj_dump,json=objDump,proto3,oneof"`
}

type Spec_Opaque struct {
	Opaque *Opaque `protobuf:"bytes,5,opt,name=opaque,proto3,oneof"`
}

func (*Spec_Attr) isSpec_Data() {}

func (*Spec_Block) isSpec_Data() {}

func (*Spec_ObjSpec) isSpec_Data() {}

func (*Spec_ObjDump) isSpec_Data() {}

func (*Spec_Opaque) isSpec_Data() {}

type NamedSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*NamedSpec_Attr
	//	*NamedSpec_Block
	//	*NamedSpec_Named
	Data isNamedSpec_Data `protobuf_oneof:"data"`
}

func (x *NamedSpec) Reset() {
	*x = NamedSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamedSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedSpec) ProtoMessage() {}

func (x *NamedSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedSpec.ProtoReflect.Descriptor instead.
func (*NamedSpec) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (m *NamedSpec) GetData() isNamedSpec_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *NamedSpec) GetAttr() *Attr {
	if x, ok := x.GetData().(*NamedSpec_Attr); ok {
		return x.Attr
	}
	return nil
}

func (x *NamedSpec) GetBlock() *Block {
	if x, ok := x.GetData().(*NamedSpec_Block); ok {
		return x.Block
	}
	return nil
}

func (x *NamedSpec) GetNamed() *Namer {
	if x, ok := x.GetData().(*NamedSpec_Named); ok {
		return x.Named
	}
	return nil
}

type isNamedSpec_Data interface {
	isNamedSpec_Data()
}

type NamedSpec_Attr struct {
	Attr *Attr `protobuf:"bytes,1,opt,name=attr,proto3,oneof"`
}

type NamedSpec_Block struct {
	Block *Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type NamedSpec_Named struct {
	Named *Namer `protobuf:"bytes,3,opt,name=named,proto3,oneof"`
}

func (*NamedSpec_Attr) isNamedSpec_Data() {}

func (*NamedSpec_Block) isNamedSpec_Data() {}

func (*NamedSpec_Named) isNamedSpec_Data() {}

type Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       *CtyType  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DefaultVal *CtyValue `protobuf:"bytes,3,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	ExampleVal *CtyValue `protobuf:"bytes,4,opt,name=example_val,json=exampleVal,proto3" json:"example_val,omitempty"`
	Doc        string    `protobuf:"bytes,5,opt,name=doc,proto3" json:"doc,omitempty"`
	Required   bool      `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Attr) Reset() {
	*x = Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *Attr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attr) GetType() *CtyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Attr) GetDefaultVal() *CtyValue {
	if x != nil {
		return x.DefaultVal
	}
	return nil
}

func (x *Attr) GetExampleVal() *CtyValue {
	if x != nil {
		return x.ExampleVal
	}
	return nil
}

func (x *Attr) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Attr) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nested   *Spec  `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	Doc      string `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	Required bool   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Block) GetNested() *Spec {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Block) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *Block) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Specs []*NamedSpec `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *Object) GetSpecs() []*NamedSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type ObjDump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doc string `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
}

func (x *ObjDump) Reset() {
	*x = ObjDump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjDump) ProtoMessage() {}

func (x *ObjDump) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjDump.ProtoReflect.Descriptor instead.
func (*ObjDump) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *ObjDump) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type Opaque struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *HclSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Doc  string   `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
}

func (x *Opaque) Reset() {
	*x = Opaque{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Opaque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opaque) ProtoMessage() {}

func (x *Opaque) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opaque.ProtoReflect.Descriptor instead.
func (*Opaque) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{6}
}

func (x *Opaque) GetSpec() *HclSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Opaque) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type Namer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec *Spec  `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Namer) Reset() {
	*x = Namer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginapi_v1_spec_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namer) ProtoMessage() {}

func (x *Namer) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_v1_spec_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namer.ProtoReflect.Descriptor instead.
func (*Namer) Descriptor() ([]byte, []int) {
	return file_pluginapi_v1_spec_proto_rawDescGZIP(), []int{7}
}

func (x *Namer) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Namer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pluginapi_v1_spec_proto protoreflect.FileDescriptor

var file_pluginapi_v1_spec_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x63, 0x6c, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x04,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x48, 0x00, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x2b,
	0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x31, 0x0a, 0x08, 0x6f,
	0x62, 0x6a, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x53, 0x70, 0x65, 0x63, 0x12, 0x32,
	0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x62, 0x6a, 0x44, 0x75, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x44, 0x75,
	0x6d, 0x70, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x70, 0x61, 0x71,
	0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x4e,
	0x61, 0x6d, 0x65, 0x64, 0x53, 0x70, 0x65, 0x63, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x48, 0x00, 0x52, 0x04, 0x61, 0x74,
	0x74, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x2b, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x61,
	0x6d, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xe5, 0x01, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x0b,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x74, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x0a, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x75, 0x0a, 0x05,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x06, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x37, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2d, 0x0a,
	0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x61, 0x6d, 0x65,
	0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x22, 0x1b, 0x0a, 0x07,
	0x4f, 0x62, 0x6a, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x22, 0x45, 0x0a, 0x06, 0x4f, 0x70, 0x61,
	0x71, 0x75, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x63, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63,
	0x22, 0x43, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0xaf, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x53, 0x70, 0x65, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x6b, 0x2d, 0x69,
	0x6f, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02,
	0x0c, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0c,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x18, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x61, 0x70, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pluginapi_v1_spec_proto_rawDescOnce sync.Once
	file_pluginapi_v1_spec_proto_rawDescData = file_pluginapi_v1_spec_proto_rawDesc
)

func file_pluginapi_v1_spec_proto_rawDescGZIP() []byte {
	file_pluginapi_v1_spec_proto_rawDescOnce.Do(func() {
		file_pluginapi_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_pluginapi_v1_spec_proto_rawDescData)
	})
	return file_pluginapi_v1_spec_proto_rawDescData
}

var file_pluginapi_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pluginapi_v1_spec_proto_goTypes = []interface{}{
	(*Spec)(nil),      // 0: pluginapi.v1.Spec
	(*NamedSpec)(nil), // 1: pluginapi.v1.NamedSpec
	(*Attr)(nil),      // 2: pluginapi.v1.Attr
	(*Block)(nil),     // 3: pluginapi.v1.Block
	(*Object)(nil),    // 4: pluginapi.v1.Object
	(*ObjDump)(nil),   // 5: pluginapi.v1.ObjDump
	(*Opaque)(nil),    // 6: pluginapi.v1.Opaque
	(*Namer)(nil),     // 7: pluginapi.v1.Namer
	(*CtyType)(nil),   // 8: pluginapi.v1.CtyType
	(*CtyValue)(nil),  // 9: pluginapi.v1.CtyValue
	(*HclSpec)(nil),   // 10: pluginapi.v1.HclSpec
}
var file_pluginapi_v1_spec_proto_depIdxs = []int32{
	2,  // 0: pluginapi.v1.Spec.attr:type_name -> pluginapi.v1.Attr
	3,  // 1: pluginapi.v1.Spec.block:type_name -> pluginapi.v1.Block
	4,  // 2: pluginapi.v1.Spec.obj_spec:type_name -> pluginapi.v1.Object
	5,  // 3: pluginapi.v1.Spec.obj_dump:type_name -> pluginapi.v1.ObjDump
	6,  // 4: pluginapi.v1.Spec.opaque:type_name -> pluginapi.v1.Opaque
	2,  // 5: pluginapi.v1.NamedSpec.attr:type_name -> pluginapi.v1.Attr
	3,  // 6: pluginapi.v1.NamedSpec.block:type_name -> pluginapi.v1.Block
	7,  // 7: pluginapi.v1.NamedSpec.named:type_name -> pluginapi.v1.Namer
	8,  // 8: pluginapi.v1.Attr.type:type_name -> pluginapi.v1.CtyType
	9,  // 9: pluginapi.v1.Attr.default_val:type_name -> pluginapi.v1.CtyValue
	9,  // 10: pluginapi.v1.Attr.example_val:type_name -> pluginapi.v1.CtyValue
	0,  // 11: pluginapi.v1.Block.nested:type_name -> pluginapi.v1.Spec
	1,  // 12: pluginapi.v1.Object.specs:type_name -> pluginapi.v1.NamedSpec
	10, // 13: pluginapi.v1.Opaque.spec:type_name -> pluginapi.v1.HclSpec
	0,  // 14: pluginapi.v1.Namer.spec:type_name -> pluginapi.v1.Spec
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pluginapi_v1_spec_proto_init() }
func file_pluginapi_v1_spec_proto_init() {
	if File_pluginapi_v1_spec_proto != nil {
		return
	}
	file_pluginapi_v1_hclspec_proto_init()
	file_pluginapi_v1_cty_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pluginapi_v1_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamedSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjDump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Opaque); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginapi_v1_spec_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pluginapi_v1_spec_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Spec_Attr)(nil),
		(*Spec_Block)(nil),
		(*Spec_ObjSpec)(nil),
		(*Spec_ObjDump)(nil),
		(*Spec_Opaque)(nil),
	}
	file_pluginapi_v1_spec_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*NamedSpec_Attr)(nil),
		(*NamedSpec_Block)(nil),
		(*NamedSpec_Named)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pluginapi_v1_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginapi_v1_spec_proto_goTypes,
		DependencyIndexes: file_pluginapi_v1_spec_proto_depIdxs,
		MessageInfos:      file_pluginapi_v1_spec_proto_msgTypes,
	}.Build()
	File_pluginapi_v1_spec_proto = out.File
	file_pluginapi_v1_spec_proto_rawDesc = nil
	file_pluginapi_v1_spec_proto_goTypes = nil
	file_pluginapi_v1_spec_proto_depIdxs = nil
}
