// Code generated by mockery v2.42.1. DO NOT EDIT.

package crowdstrike_mocks

import (
	cspm_registration "github.com/crowdstrike/gofalcon/falcon/client/cspm_registration"
	mock "github.com/stretchr/testify/mock"
)

// CspmRegistrationClient is an autogenerated mock type for the CspmRegistrationClient type
type CspmRegistrationClient struct {
	mock.Mock
}

type CspmRegistrationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CspmRegistrationClient) EXPECT() *CspmRegistrationClient_Expecter {
	return &CspmRegistrationClient_Expecter{mock: &_m.Mock}
}

// GetConfigurationDetections provides a mock function with given fields: params, opts
func (_m *CspmRegistrationClient) GetConfigurationDetections(params *cspm_registration.GetConfigurationDetectionsParams, opts ...cspm_registration.ClientOption) (*cspm_registration.GetConfigurationDetectionsOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigurationDetections")
	}

	var r0 *cspm_registration.GetConfigurationDetectionsOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*cspm_registration.GetConfigurationDetectionsParams, ...cspm_registration.ClientOption) (*cspm_registration.GetConfigurationDetectionsOK, error)); ok {
		return rf(params, opts...)
	}
	if rf, ok := ret.Get(0).(func(*cspm_registration.GetConfigurationDetectionsParams, ...cspm_registration.ClientOption) *cspm_registration.GetConfigurationDetectionsOK); ok {
		r0 = rf(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cspm_registration.GetConfigurationDetectionsOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*cspm_registration.GetConfigurationDetectionsParams, ...cspm_registration.ClientOption) error); ok {
		r1 = rf(params, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CspmRegistrationClient_GetConfigurationDetections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigurationDetections'
type CspmRegistrationClient_GetConfigurationDetections_Call struct {
	*mock.Call
}

// GetConfigurationDetections is a helper method to define mock.On call
//   - params *cspm_registration.GetConfigurationDetectionsParams
//   - opts ...cspm_registration.ClientOption
func (_e *CspmRegistrationClient_Expecter) GetConfigurationDetections(params interface{}, opts ...interface{}) *CspmRegistrationClient_GetConfigurationDetections_Call {
	return &CspmRegistrationClient_GetConfigurationDetections_Call{Call: _e.mock.On("GetConfigurationDetections",
		append([]interface{}{params}, opts...)...)}
}

func (_c *CspmRegistrationClient_GetConfigurationDetections_Call) Run(run func(params *cspm_registration.GetConfigurationDetectionsParams, opts ...cspm_registration.ClientOption)) *CspmRegistrationClient_GetConfigurationDetections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]cspm_registration.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(cspm_registration.ClientOption)
			}
		}
		run(args[0].(*cspm_registration.GetConfigurationDetectionsParams), variadicArgs...)
	})
	return _c
}

func (_c *CspmRegistrationClient_GetConfigurationDetections_Call) Return(_a0 *cspm_registration.GetConfigurationDetectionsOK, _a1 error) *CspmRegistrationClient_GetConfigurationDetections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CspmRegistrationClient_GetConfigurationDetections_Call) RunAndReturn(run func(*cspm_registration.GetConfigurationDetectionsParams, ...cspm_registration.ClientOption) (*cspm_registration.GetConfigurationDetectionsOK, error)) *CspmRegistrationClient_GetConfigurationDetections_Call {
	_c.Call.Return(run)
	return _c
}

// NewCspmRegistrationClient creates a new instance of CspmRegistrationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCspmRegistrationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CspmRegistrationClient {
	mock := &CspmRegistrationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
