// Code generated by mockery v2.42.1. DO NOT EDIT.

package microsoft_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// MicrosoftGraphClient is an autogenerated mock type for the MicrosoftGraphClient type
type MicrosoftGraphClient struct {
	mock.Mock
}

type MicrosoftGraphClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MicrosoftGraphClient) EXPECT() *MicrosoftGraphClient_Expecter {
	return &MicrosoftGraphClient_Expecter{mock: &_m.Mock}
}

// QueryGraph provides a mock function with given fields: ctx, endpoint, queryParams
func (_m *MicrosoftGraphClient) QueryGraph(ctx context.Context, endpoint string, queryParams url.Values) (interface{}, error) {
	ret := _m.Called(ctx, endpoint, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for QueryGraph")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) (interface{}, error)); ok {
		return rf(ctx, endpoint, queryParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) interface{}); ok {
		r0 = rf(ctx, endpoint, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values) error); ok {
		r1 = rf(ctx, endpoint, queryParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MicrosoftGraphClient_QueryGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryGraph'
type MicrosoftGraphClient_QueryGraph_Call struct {
	*mock.Call
}

// QueryGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
//   - queryParams url.Values
func (_e *MicrosoftGraphClient_Expecter) QueryGraph(ctx interface{}, endpoint interface{}, queryParams interface{}) *MicrosoftGraphClient_QueryGraph_Call {
	return &MicrosoftGraphClient_QueryGraph_Call{Call: _e.mock.On("QueryGraph", ctx, endpoint, queryParams)}
}

func (_c *MicrosoftGraphClient_QueryGraph_Call) Run(run func(ctx context.Context, endpoint string, queryParams url.Values)) *MicrosoftGraphClient_QueryGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(url.Values))
	})
	return _c
}

func (_c *MicrosoftGraphClient_QueryGraph_Call) Return(result interface{}, err error) *MicrosoftGraphClient_QueryGraph_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MicrosoftGraphClient_QueryGraph_Call) RunAndReturn(run func(context.Context, string, url.Values) (interface{}, error)) *MicrosoftGraphClient_QueryGraph_Call {
	_c.Call.Return(run)
	return _c
}

// NewMicrosoftGraphClient creates a new instance of MicrosoftGraphClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMicrosoftGraphClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MicrosoftGraphClient {
	mock := &MicrosoftGraphClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
