// Code generated by mockery v2.52.2. DO NOT EDIT.

package microsoft_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	plugindata "github.com/blackstork-io/fabric/plugin/plugindata"

	url "net/url"
)

// MicrosoftGraphClient is an autogenerated mock type for the MicrosoftGraphClient type
type MicrosoftGraphClient struct {
	mock.Mock
}

type MicrosoftGraphClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MicrosoftGraphClient) EXPECT() *MicrosoftGraphClient_Expecter {
	return &MicrosoftGraphClient_Expecter{mock: &_m.Mock}
}

// QueryObject provides a mock function with given fields: ctx, endpoint, queryParams
func (_m *MicrosoftGraphClient) QueryObject(ctx context.Context, endpoint string, queryParams url.Values) (plugindata.Data, error) {
	ret := _m.Called(ctx, endpoint, queryParams)

	if len(ret) == 0 {
		panic("no return value specified for QueryObject")
	}

	var r0 plugindata.Data
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) (plugindata.Data, error)); ok {
		return rf(ctx, endpoint, queryParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) plugindata.Data); ok {
		r0 = rf(ctx, endpoint, queryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugindata.Data)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values) error); ok {
		r1 = rf(ctx, endpoint, queryParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MicrosoftGraphClient_QueryObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryObject'
type MicrosoftGraphClient_QueryObject_Call struct {
	*mock.Call
}

// QueryObject is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
//   - queryParams url.Values
func (_e *MicrosoftGraphClient_Expecter) QueryObject(ctx interface{}, endpoint interface{}, queryParams interface{}) *MicrosoftGraphClient_QueryObject_Call {
	return &MicrosoftGraphClient_QueryObject_Call{Call: _e.mock.On("QueryObject", ctx, endpoint, queryParams)}
}

func (_c *MicrosoftGraphClient_QueryObject_Call) Run(run func(ctx context.Context, endpoint string, queryParams url.Values)) *MicrosoftGraphClient_QueryObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(url.Values))
	})
	return _c
}

func (_c *MicrosoftGraphClient_QueryObject_Call) Return(object plugindata.Data, err error) *MicrosoftGraphClient_QueryObject_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MicrosoftGraphClient_QueryObject_Call) RunAndReturn(run func(context.Context, string, url.Values) (plugindata.Data, error)) *MicrosoftGraphClient_QueryObject_Call {
	_c.Call.Return(run)
	return _c
}

// QueryObjects provides a mock function with given fields: ctx, endpoint, queryParams, size
func (_m *MicrosoftGraphClient) QueryObjects(ctx context.Context, endpoint string, queryParams url.Values, size int) (plugindata.List, error) {
	ret := _m.Called(ctx, endpoint, queryParams, size)

	if len(ret) == 0 {
		panic("no return value specified for QueryObjects")
	}

	var r0 plugindata.List
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values, int) (plugindata.List, error)); ok {
		return rf(ctx, endpoint, queryParams, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values, int) plugindata.List); ok {
		r0 = rf(ctx, endpoint, queryParams, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugindata.List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values, int) error); ok {
		r1 = rf(ctx, endpoint, queryParams, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MicrosoftGraphClient_QueryObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryObjects'
type MicrosoftGraphClient_QueryObjects_Call struct {
	*mock.Call
}

// QueryObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - endpoint string
//   - queryParams url.Values
//   - size int
func (_e *MicrosoftGraphClient_Expecter) QueryObjects(ctx interface{}, endpoint interface{}, queryParams interface{}, size interface{}) *MicrosoftGraphClient_QueryObjects_Call {
	return &MicrosoftGraphClient_QueryObjects_Call{Call: _e.mock.On("QueryObjects", ctx, endpoint, queryParams, size)}
}

func (_c *MicrosoftGraphClient_QueryObjects_Call) Run(run func(ctx context.Context, endpoint string, queryParams url.Values, size int)) *MicrosoftGraphClient_QueryObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(url.Values), args[3].(int))
	})
	return _c
}

func (_c *MicrosoftGraphClient_QueryObjects_Call) Return(objects plugindata.List, err error) *MicrosoftGraphClient_QueryObjects_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MicrosoftGraphClient_QueryObjects_Call) RunAndReturn(run func(context.Context, string, url.Values, int) (plugindata.List, error)) *MicrosoftGraphClient_QueryObjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMicrosoftGraphClient creates a new instance of MicrosoftGraphClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMicrosoftGraphClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MicrosoftGraphClient {
	mock := &MicrosoftGraphClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
