# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

name: docs

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '.markdownlint.yaml'
      - '.vale.ini'
      - '.github/styles/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - '**.md'
      - '.markdownlint.yaml'
      - '.vale.ini'
      - '.github/styles/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

concurrency:
  group: docs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # https://github.com/DavidAnson/markdownlint-cli2-action
  markdownlint-cli:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24
        with:
          globs: '**/*.md'
          config: .markdownlint.yaml

  # https://github.com/vale-cli/vale-action
  vale:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: vale-cli/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3
        with:
          version: 3.17.0
          files: all
          fail_on_error: true
