# Copyright 2026 BlackStork BV
#
# Use of this software is governed by the Business Source License included in the
# file LICENSE and at www.mariadb.com/bsl11.
#
# As of the Change Date specified in that file, in accordance with the Business
# Source License, use of this software will be governed by the Apache License,
# Version 2.0, included in the file .licenses/APACHE-2.0.txt.

name: Full PR checks

on:
  workflow_call:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["stable", "oldstable"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
      # Run integration tests (testcontainers) on ubuntu
      - run: go test -race -v -timeout 2m ${{ !startsWith(matrix.os, 'ubuntu') && '-short' || '' }} ./...

  builds:
    strategy:
      matrix:
        go-version: ["stable", "oldstable"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build blackstork-cli and plugins
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: v2.18.0
          args: build --snapshot --clean --single-target
